### ISSUE TITLE
AVX2 required to use pnumpy

### ISSUE THREAD

**Issue by mattip** [Quansight/numpy-threading-extensions#104] opened 2020-12-15 14:47 UTC
It turns tox was not running any CI. I started redoing this in pr ~gh-103~ gh-102 but it seems macOS is crashing on import. The [traceback](https://github.com/Quansight/numpy-threading-extensions/pull/102/checks?check_run_id=1557695367#step:6:29) seems to indicate it is on [line 50 of `__init__.py`](https://github.com/Quansight/numpy-threading-extensions/blob/main/src/pnumpy/__init__.py#L50) which is in `_pnumpy.initialize()`

**Comment by mattip** [comment] 2020-12-15 17:13
The problem may be due to missing avx2 features on the mac machines used in CI?

**Comment by mattip** [comment] 2020-12-15 18:49
Yes, AVX2 is missing. Is that going to be a hard requirement for macOS? We should document it.

**Comment by mattip** [comment] 2020-12-15 21:22
I changed the issue title pending a decision whether this is a hard requirement, in which case we should document it, or if it is not, in which case we should have some kind of dispatch mechanism to detect CPU features in real time. Note that numpy supplies that (as of version 1.19) in the `core._multiarray_umath.__cpu_features` dictionary.

**Comment by tdimitri** [comment] 2021-01-07 23:37
Part of the problem is we need to tell the MacOS compiler to compile some files without AVX2... and then compile the vector routines with AVX2 on... we need to flip AVX2 flags for just certain .cpp files.
This will allow non-AVX2 to still use threading, and still use other routines we have sped up - like sort/argsort/lexsort.

I am not an expert on how to best flip those AVX2 flags on for certain .cpp files.
For example, most C compiler have a stub to initialize their C run time ... sometimes when the AVX2 flag is on, the c runtime routines for things like memset/memcpy/etc are also AVX2 enabled.  So c run time comes up... clears memory or whatnot, crashes immediately... and sometimes not even a chance to check the CPU flags.

**Comment by mattip** [comment] 2021-01-18 22:45
I think macos builds are failing differently now: something about mergesort. We should either decide we do not support macos and skip the builds or fix this. We cannot release a version with broken builds

**Comment by tdimitri** [comment] 2021-01-19 14:20
I needed to put a forward declaration for the mac compiler for a new routine I wrote.  I checked in the code and it builds.
The main culprit is 
1) macos github tests (appear to) run with lack of AVX2 support, therefore we can never test Mac on github, we can only build it.
So to me, this is a reason to pre-release on Mac so we can download it and better evaluate.  I have a Mac with AVX2 support.

We can also compile without the -avx2 flag, then run code to detect the functionality on the chip, and if missing, not enable atop (but that just leaves us back to the main problem -- cannot automate mac os testing on github).

**Comment by mattip-q** [comment] 2021-01-20 15:28
I think we should build with the flag. Can the python `init` routine add an exception handler?

**Comment by mattip** [comment] 2021-01-20 15:29
I think we should build with the flag. Can the python init routine add an exception handler?

**Comment by tdimitri** [comment] 2021-01-20 16:18
If you are referring to the python __init__.py, then yes I think that is a good idea.  We can load numpy first, possibly check numpy version, get the cpu_flags from numpy and then check for AVX2.  Then we will not even load the pnumpy DLL/SO, because as soon as we load it, it could call a c runtime or dll init routine, which might have AVX2 code (if built with -mavx2 flag), which might then hit bad opcode exception.
However, this will still not fix that Mac needs AVX2 to run, to pass the test.  This only prevents a Mac user from experiencing a crash (which is good).
Also, it's not quite true that we need AVX2 to thread Mac.  Certainly existing numpy code can be threaded.  The new sort routines don't need AVX2 either.  
I am not too worried as AVX2 was introduced in 2012... Some 9 years ago and if a user really wants performance, they should updating an 8 year old CPU.
NOTE just tested this and it works.  Mac gets the message " ValueError: pnumpy requires a CPU with AVX2 capability to work" which explains that Macs in github dont have AVX2.

**Comment by mattip** [comment] 2021-01-21 19:18
I think this is closed by #135

**Closed** 2021-01-26 06:53 UTC
Labels: question
